#!/usr/bin/env bash
# generate_env.sh — Reads Terraform outputs and writes .env files
# for Airflow (and any other downstream tool that needs GCP config).
#
# Usage:  cd terraform && bash generate_env.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AIRFLOW_ENV="${SCRIPT_DIR}/../airflow/.env"

echo "Reading Terraform outputs..."

GCP_PROJECT_ID=$(terraform output -raw project_id)
GCS_BUCKET_NAME=$(terraform output -raw gcs_bucket_name)
BQ_DATASET_ID=$(terraform output -raw bq_dataset_id)
GCP_REGION=$(terraform output -raw region)
GCP_LOCATION=$(terraform output -raw location)

# ── Write Airflow .env ──────────────────────────────────────────────
cat > "${AIRFLOW_ENV}" <<EOF
# Auto-generated by terraform/generate_env.sh — do not edit manually
AIRFLOW_UID=$(id -u)

# GCP Configuration (from Terraform outputs)
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
GCS_PREFIX=Milano-Cortina-2026
BQ_DATASET_ID=${BQ_DATASET_ID}
GCP_REGION=${GCP_REGION}
GCP_LOCATION=${GCP_LOCATION}
EOF

echo "✓ Written: ${AIRFLOW_ENV}"
cat "${AIRFLOW_ENV}"
